spring:
  application:
    name: ichong-starter-testdemo
server:
  port: 18081

xxl-job:
  username: admin
  password: 123456
  url: http://127.0.0.1:8080/xxl-job-admin



singleServerConfig:
  idleConnectionTimeout: 10000
  connectTimeout: 10000
  timeout: 3000
  retryAttempts: 3
  retryInterval: 1500
  # 如果Redis服务端配置有密码需要替换password的值
  password: null
  subscriptionsPerConnection: 5
  clientName: null
  # 替换为自己真实Redis服务端连接
  address: "redis://127.0.0.1:6379"
  subscriptionConnectionMinimumIdleSize: 1
  subscriptionConnectionPoolSize: 50
  connectionMinimumIdleSize: 24
  connectionPoolSize: 64
  database: 0
  dnsMonitoringInterval: 5000
threads: 16
nettyThreads: 32
codec: "!<org.redisson.codec.MarshallingCodec> {}"
transportMode: "NIO"

